/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */
package com.jony.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 7;
  /** RegularExpression Id. */
  int DROP = 8;
  /** RegularExpression Id. */
  int SELECT = 9;
  /** RegularExpression Id. */
  int INSERT = 10;
  /** RegularExpression Id. */
  int UPDATE = 11;
  /** RegularExpression Id. */
  int SET = 12;
  /** RegularExpression Id. */
  int DELETE = 13;
  /** RegularExpression Id. */
  int DISTINCT = 14;
  /** RegularExpression Id. */
  int VALUES = 15;
  /** RegularExpression Id. */
  int FROM = 16;
  /** RegularExpression Id. */
  int WHERE = 17;
  /** RegularExpression Id. */
  int ORDERBY = 18;
  /** RegularExpression Id. */
  int NULL = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int LIKE = 21;
  /** RegularExpression Id. */
  int AND = 22;
  /** RegularExpression Id. */
  int NOT = 23;
  /** RegularExpression Id. */
  int DATATYPE = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;
  /** RegularExpression Id. */
  int INTEGER = 26;
  /** RegularExpression Id. */
  int LETTER = 27;
  /** RegularExpression Id. */
  int NUMERAL = 28;
  /** RegularExpression Id. */
  int LPAREN = 29;
  /** RegularExpression Id. */
  int RPAREN = 30;
  /** RegularExpression Id. */
  int LBRACE = 31;
  /** RegularExpression Id. */
  int RBRACE = 32;
  /** RegularExpression Id. */
  int LBRACKET = 33;
  /** RegularExpression Id. */
  int RBRACKET = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int DOT = 36;
  /** RegularExpression Id. */
  int PLUS = 37;
  /** RegularExpression Id. */
  int MINUS = 38;
  /** RegularExpression Id. */
  int STAR = 39;
  /** RegularExpression Id. */
  int SLASH = 40;
  /** RegularExpression Id. */
  int LT = 41;
  /** RegularExpression Id. */
  int GT = 42;
  /** RegularExpression Id. */
  int EQ = 43;
  /** RegularExpression Id. */
  int COMP_OP = 44;
  /** RegularExpression Id. */
  int QUOTE = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\\\\"",
    "\"\\t\"",
    "\" \"",
    "\"Create Table\"",
    "\"Drop Table\"",
    "\"Select\"",
    "\"Insert Into\"",
    "\"Update\"",
    "\"Set\"",
    "\"Delete From\"",
    "\"Distinct\"",
    "\"Values\"",
    "\"From\"",
    "\"Where\"",
    "\"Order By\"",
    "\"Null\"",
    "\"OR\"",
    "\"LIKE\"",
    "\"AND\"",
    "\"NOT\"",
    "<DATATYPE>",
    "<DIGIT>",
    "<INTEGER>",
    "<LETTER>",
    "<NUMERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "<COMP_OP>",
    "<QUOTE>",
  };

}
